source 'http://rubygems.org'

gem 'sinatra', :require => 'sinatra/base'

##########################
# markdown libs/engines

gem 'kramdown'
gem 'redcarpet'
gem 'maruku'
gem 'bluecloth'

# gem 'rdiscount'  # compilation error on heroku; sorry excluded for now

# gem 'rpeg-markdown'  # compilation error w/ bundler - exclude for now; still active, anyway?


###################
# more libs

gem 'textutils'
gem 'props'

gem 'markdown'

