require 'hoe'
require './lib/markdown/cli/version.rb'

Hoe.spec 'markdown-tools' do

  self.version = MarkdownCli::VERSION

  self.summary = 'markdown-tools gem - markdown command line tools'
  self.description = summary

  self.urls    = ['https://github.com/rubylibs/markdown-tools']

  self.author  = 'Gerald Bauer'
  self.email   = 'webslideshow@googlegroups.com'
  
  self.extra_deps = [
    ['markdown'],
    ['markdown-service'],
  ]

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'HISTORY.md'

  self.licenses = ['Public Domain']

  self.spec_extras = {
   required_ruby_version: '>= 1.9.2'
  }

end
